---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "checks.updown.io"
spec:
  group: "updown.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "checks"
    singular: "check"
    kind: "Check"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["url"]
          properties:
            url:
              type: "string"
            period:
              type: "integer"
            apdexT:
              type: "float"
            enabled:
              type: "boolean"
            published:
              type: "boolean"
            alias:
              type: "string"
            stringMatch:
              type: "string"
            muteUntil:
              type: "string"
            disabledLocations:
              type: array
              items:
                type: string
            customHeaders:
              type: array
              items:
                properties:
                  key:
                    type: string
                  value:
                    type: string

              