sudo: required
services:
  - docker
language: go
go:
- '1.x'
install:
- curl https://glide.sh/get | sh
- glide up -v

deploy:
  provider: script
  script: bash deploy_docker_hub.sh
  on:
    tags: true