sudo: required
services:
  - docker
language: go
go:
- '1.x'
env:
  - CGO_ENABLED=0
install:
- curl https://glide.sh/get | sh
- glide up -v

deploy:
  provider: script
  script: bash deploy_docker_hub.sh
  skip_cleanup: true
  on:
    tags: true