---
apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "checks.updown.io"
spec:
  group: "updown.io"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "checks"
    singular: "check"
    kind: "Check"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["url"]
          properties:
            url:
              type: "string"