---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-updown-io-controller

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: updown-checks-reader
rules:
  - apiGroups: ["updown.io"]
    resources: ["checks"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-updown-io-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: updown-checks-reader
subjects:
  - name: kubernetes-updown-io-controller
    kind: ServiceAccount
    namespace: default

